index:
    path: /
    controller: App\Controller\DefaultController::index

articles_list:
    path: /articles
    controller: App\Controller\ArticleController::index

concurrents_list:
    path: /concurrents
    controller: App\Controller\ConcurrentController::index

concurrents_list_etat_get:
    path: /concurrents/{etat}
    controller: App\Controller\ConcurrentController::indexEtatGet
    methods: GET

concurrents_list_etat_post:
    path: /concurrents/etat
    controller: App\Controller\ConcurrentController::indexEtatPost
    methods: POST

articles_vendeur_list:
    path: /articles/vendeur
    controller: App\Controller\ArticleVendeurController::index

placer_concurrence_form:
    path: /article/{id}/concurrencer
    controller: App\Controller\ConcurrentController::placerForm

placer_concurrence_action:
    path: /article/concurrencer/action
    controller: App\Controller\ConcurrentController::placerAction
    methods: POST
